# Generated by Django 5.2.3 on 2025-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORY_code', models.CharField(max_length=4, unique=True)),
                ('CATEGORY_description', models.CharField(max_length=100)),
                ('CATEGORY_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP_code', models.CharField(max_length=10, unique=True)),
                ('GROUP_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('ITEM_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ITEM_code', models.CharField(max_length=10, unique=True)),
                ('ITEM_group', models.CharField(max_length=10, unique=True)),
                ('ITEM_type', models.CharField(max_length=10, unique=True)),
                ('ITEM_category', models.IntegerField()),
                ('ITEM_description', models.CharField(blank=True, max_length=600, null=True)),
                ('ITEM_uom', models.IntegerField(blank=True, null=True)),
                ('ITEM_reorder_level', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_reorder_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_max_level', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_min_level', models.DecimalField(blank=True, decimal_places=3, max_digits=23, null=True)),
                ('ITEM_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_min_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_normal_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_cash_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_credit_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('ITEM_invoicable', models.BooleanField(blank=True, null=True)),
                ('ITEM_active', models.BooleanField(blank=True, null=True)),
                ('ITEM_warranty', models.IntegerField(blank=True, null=True)),
                ('ITEM_has_barcode', models.BooleanField(blank=True, null=True)),
                ('ITEM_barcode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'INV_Item_Master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_code', models.CharField(max_length=10, unique=True)),
                ('TYPE_description', models.CharField(max_length=100)),
                ('TYPE_active', models.BooleanField(default=True)),
                ('TYPE_use_order_form', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
