# Generated by Django 5.2.3 on 2025-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemmaster_item_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='housing_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='power',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='temp_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='voltage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
