# Generated by Django 5.2.3 on 2025-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemmaster_housing_material_itemmaster_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='ITEM_type',
            field=models.CharField(choices=[('warranty', 'Warranty'), ('non-warranty', 'Non-Warranty'), ('utensil', 'Utensil'), ('spare', 'Spare Part')], max_length=12),
        ),
    ]
