# Generated by Django 5.2.3 on 2025-06-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemmaster_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUH_code', models.CharField(max_length=20, unique=True)),
                ('QUH_pay_type', models.CharField(blank=True, max_length=20, null=True)),
                ('QUH_validity', models.IntegerField()),
                ('QUH_location', models.CharField(blank=True, max_length=100, null=True)),
                ('QUH_your_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('QUH_customer_name', models.CharField(max_length=255)),
                ('QUH_customer_address', models.TextField()),
                ('QUH_customer_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('QUH_attention', models.CharField(blank=True, max_length=100, null=True)),
                ('QUH_date', models.DateField()),
                ('QUH_quatation_date', models.DateField()),
                ('QUH_gross_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('QUH_net_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUD_line_no', models.IntegerField()),
                ('QUD_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('QUD_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('QUD_remark', models.TextField(blank=True, null=True)),
                ('QUD_warranty', models.BooleanField(default=False)),
                ('QUD_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmaster')),
                ('QUD_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.quotationheader')),
            ],
        ),
    ]
