# Generated by Django 5.2.3 on 2025-06-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_quotationheader_quotationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMER_code', models.CharField(max_length=15, unique=True)),
                ('CUSTOMER_group', models.IntegerField()),
                ('CUSTOMER_area', models.IntegerField()),
                ('CUSTOMER_name', models.CharField(max_length=150)),
                ('CUSTOMER_title', models.CharField(blank=True, max_length=20, null=True)),
                ('CUSTOMER_title_id', models.IntegerField(blank=True, null=True)),
                ('CUSTOMER_address', models.CharField(blank=True, max_length=400, null=True)),
                ('CUSTOMER_tele_1', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_tele_2', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_tele_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('CUSTOMER_contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('CUSTOMER_contact_person_title', models.CharField(blank=True, max_length=20, null=True)),
                ('CUSTOMER_contact_person_title_id', models.IntegerField(blank=True, null=True)),
                ('CUSTOMER_term', models.IntegerField()),
                ('CUSTOMER_vat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('CUSTOMER_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('CUSTOMER_creidt_period', models.BigIntegerField(blank=True, null=True)),
                ('CUSTOMER_account_number', models.IntegerField()),
                ('CUSTOMER_lock', models.BooleanField(default=False)),
                ('CUSTOMER_created_user_session', models.BigIntegerField(blank=True, null=True)),
                ('CUSTOMER_created_datetime', models.DateTimeField(blank=True, null=True)),
                ('CUSTOMER_last_edited_user_session', models.BigIntegerField(blank=True, null=True)),
                ('CUSTOMER_last_edited_datetime', models.DateTimeField(blank=True, null=True)),
                ('CUSTOMER_prefix_id', models.BigIntegerField()),
                ('CUSTOMER_prefix_number', models.IntegerField()),
            ],
        ),
    ]
