# Generated by Django 5.2.3 on 2025-07-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('INVOICE_H_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('INVOICE_H_location', models.CharField(max_length=100)),
                ('INVOICE_H_number', models.CharField(max_length=20)),
                ('INVOICE_H_code', models.CharField(max_length=20)),
                ('INVOICE_H_token', models.CharField(blank=True, max_length=50, null=True)),
                ('INVOICE_H_sales_rep', models.CharField(blank=True, max_length=100, null=True)),
                ('INVOICE_H_datetime', models.DateTimeField(auto_now_add=True)),
                ('INVOICE_H_payment_term', models.CharField(max_length=20)),
                ('INVOICE_H_total_discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('INVOICE_H_total_discount_type', models.CharField(choices=[('Value', 'Value'), ('Percentage', 'Percentage')], max_length=10)),
                ('INVOICE_H_total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('INVOICE_H_processed', models.BooleanField(default=False)),
                ('INVOICE_H_grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('INVOICE_H_commision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('INVOICE_H_user', models.CharField(max_length=100)),
                ('INVOICE_H_type', models.CharField(default='Cash', max_length=20)),
                ('INVOICE_H_remakrs', models.TextField(blank=True, null=True)),
                ('INVOICE_H_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
            ],
            options={
                'db_table': 'INV_Invoice_H',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('INVOICE_D_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('INVOICE_D_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('INVOICE_D_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('INVOICE_D_discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('INVOICE_D_discount_type', models.CharField(choices=[('Value', 'Value'), ('Percentage', 'Percentage')], max_length=10)),
                ('INVOICE_D_discount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('INVOICE_D_warranty_month', models.IntegerField(default=0)),
                ('INVOICE_D_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('INVOICE_D_vat_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('INVOICE_D_sales_rep', models.CharField(blank=True, max_length=100, null=True)),
                ('INVOICE_D_qty_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('INVOICE_D_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmaster')),
                ('INVOICE_D_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.invoiceheader')),
            ],
            options={
                'db_table': 'INV_Invoice_D',
            },
        ),
    ]
