# Generated by Django 5.2.3 on 2025-07-28 06:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_invoiceheader_invoicedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
